name: CI/CD Workflow

on:
  push:
    branches:
      - main  # ou outra branch que você deseje
  pull_request:
    branches:
      - main  # ou outra branch que você deseje

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t jordajesus/quick-serve-api-pedido:1.0 .

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 jordajesus/quick-serve-api-pedido:1.0

    - name: Wait for application to be ready
      run: |
        until curl --silent --fail http://localhost:8080/health; do
          echo "Aguardando a aplicação iniciar..."
          sleep 5
        done

    - name: Run Cucumber tests
      run: mvn test -Dcucumber.options="--tags @yourTag"
