name: Run Integration Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: backend
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/backend" >> $GITHUB_ENV
        echo "SPRING_DATASOURCE_USERNAME=postgres" >> $GITHUB_ENV
        echo "SPRING_DATASOURCE_PASSWORD=123456" >> $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        check-latest: false

    - name: Build with Maven
      run: mvn clean install

    - name: Run Integration Tests
      run: mvn test
