name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Usa o runner do GitHub Actions com Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t jordajesus/quick-serve-api-pedido:1.0 .

    - name: Run Docker container
      run: |
        # Executa o container em segundo plano, expondo a porta 8080
        docker run -d -p 8080:8080 jordajesus/quick-serve-api-pedido:1.0

    - name: Wait for application to be ready
      run: |
        # Aguarda até que a porta 8080 esteja aberta no container (via localhost)
        until nc -zv localhost 8080; do
          echo "Aguardando a aplicação iniciar..."
          sleep 5
        done

    - name: Run Cucumber tests
      run: mvn test -Dcucumber.options="--tags @yourTag"
