name: Build, Test, and Deploy

on:
  push:
    branches:
      - "*"

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: toor
          POSTGRES_DB: backend
        options: >-
          --health-cmd="pg_isready -U root -d backend"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          ${{ runner.os }}-

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..10}; do
          if pg_isready -h localhost -p 5432 -U root -d backend; then
            echo "PostgreSQL is ready!"
            break
          fi
          echo "Waiting for PostgreSQL to be ready..."
          sleep 3
        done

    - name: Build application
      run: mvn clean package

    - name: Run tests
      run: mvn test
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/backOrders
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 123456
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
