name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: backOrders
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker image
      run: docker build -t jordajesus/quick-serve-api-pedido:1.0 .

    - name: Run Docker container with PostgreSQL using bd-compose.yml
      run: |
        docker-compose -f bd-compose.yml up -d

    - name: Wait for application to be ready
      run: |
        until nc -zv localhost 8080; do
          echo "Aguardando a aplicação iniciar..."
          sleep 5
        done

    - name: Run Cucumber tests
      run: mvn test -Dcucumber.options="--tags @yourTag"
